name: E-Commerce ETL CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install general dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Install Spark dependencies
        run: |
          pip install pyspark==3.3.1 delta-spark==2.1.0

      - name: Debug directory structure and environment
        run: |
          pwd
          ls -R .
          echo $PYTHONPATH
          python -c "import sys; print(sys.path)"

      - name: Run unit tests
        env:
          PYTHONPATH: ./src
        run: |
          pytest src/tests/unit/ --verbose

      - name: Run integration tests
        env:
          PYTHONPATH: ./src
        run: |
          pytest src/tests/integration/ --verbose

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Upload glue scripts to S3
        run: |
          aws s3 cp src/glue_scripts/ s3://ecommerce-lakehouse/etl-scripts/glue_jobs/ --recursive --exclude "*" --include "*.py"
          aws s3 cp src/utils/validation.py s3://ecommerce-lakehouse/etl-scripts/glue_jobs/utils/validation.py

      - name: Deploy Lambda function
        run: |
          zip -j lambda_function.zip src/lambda_function.py
          aws lambda update-function-code --function-name ArchiveETLFiles --zip-file fileb://lambda_function.zip

      - name: Deploy Step Function
        run: |
          aws stepfunctions update-state-machine \
            --state-machine-arn arn:aws:states:eu-west-1:${{ secrets.AWS_ACCOUNT_ID }}:stateMachine:EcommerceETLPipeline \
            --definition file://src/step_functions.json \
            --role-arn arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/StepFunctionsExecutionRole