# .github/workflows/ci.yml
name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      minio:
        image: minio/minio
        env:
          MINIO_ROOT_USER: minio
          MINIO_ROOT_PASSWORD: minio123
        ports:
          - 9000:9000
          - 9001:9001
        options: --entrypoint sh -c "mkdir -p /data/test-bucket && minio server /data --console-address :9001"
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: Install dependencies
        run: |
          pip install pytest pytest-cov moto boto3 pyspark delta-spark
          pip install -e .
          
      - name: Run unit tests
        env:
          PYTHONPATH: ./src
        run: |
          pytest src/tests/unit --cov=src --cov-report=xml
          
      - name: Upload coverage
        uses: codecov/codecov-action@v1