name: E-Commerce ETL CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install general dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/requirements.txt

      - name: Install Spark dependencies
        run: |
          pip install pyspark==3.3.1 delta-spark==2.1.0

      - name: Debug directory structure and environment
        run: |
          pwd
          ls -R .
          echo $PYTHONPATH
          python -c "import sys; print(sys.path)"

      - name: Run validation unit tests
        env:
          PYTHONPATH: ./src
        run: |
          pytest src/tests/unit/test_validation.py --verbose

      - name: Run integration tests
        env:
          PYTHONPATH: ./src
        run: |
          pytest src/tests/integration/ --verbose