# .github/workflows/ci.yml
name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          
      - name: Install dependencies
        run: |
          sudo apt-get install openjdk-8-jdk -y
          pip install pyspark==3.5.0 delta-spark==2.4.0 pytest==7.4.0
          pip install -e .
          
      - name: Run tests
        run: |
          export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
          pytest tests/ --cov=src --cov-report=xml
          
      - name: Upload coverage
        uses: codecov/codecov-action@v1